# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='common',
  serialized_pb='\n\x0c\x63ommon.proto\x12\x06\x63ommon\"\"\n\x10\x43_S_DoReadyStart\x12\x0e\n\x06result\x18\x01 \x01(\x08\"\x85\x01\n\x15S_C_PlayerReadyResult\x12?\n\x0cPlayerResult\x18\x01 \x03(\x0b\x32).common.S_C_PlayerReadyResult.player_info\x1a+\n\x0bplayer_info\x12\x0c\n\x04side\x18\x01 \x02(\x07\x12\x0e\n\x06result\x18\x02 \x02(\x08\"\x1d\n\x0b\x43_S_OnProxy\x12\x0e\n\x06\x63hoice\x18\x01 \x02(\x07\"f\n\tS_C_Proxy\x12+\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x1d.common.S_C_Proxy.S_C_IsProxy\x1a,\n\x0bS_C_IsProxy\x12\x0c\n\x04side\x18\x01 \x02(\x07\x12\x0f\n\x07isproxy\x18\x02 \x02(\x08*e\n\nMSG_HEADER\x12\x16\n\x10\x43_S_DOREADYSTART\x10\x81\xc0\x02\x12\x11\n\x0b\x43_S_ONPROXY\x10\x82\xc0\x02\x12\x1b\n\x15S_C_PLAYERREADYRESULT\x10\x81\xe0\x02\x12\x0f\n\tS_C_PROXY\x10\x82\xe0\x02')

_MSG_HEADER = _descriptor.EnumDescriptor(
  name='MSG_HEADER',
  full_name='common.MSG_HEADER',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='C_S_DOREADYSTART', index=0, number=40961,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='C_S_ONPROXY', index=1, number=40962,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S_C_PLAYERREADYRESULT', index=2, number=45057,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S_C_PROXY', index=3, number=45058,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=331,
  serialized_end=432,
)

MSG_HEADER = enum_type_wrapper.EnumTypeWrapper(_MSG_HEADER)
C_S_DOREADYSTART = 40961
C_S_ONPROXY = 40962
S_C_PLAYERREADYRESULT = 45057
S_C_PROXY = 45058



_C_S_DOREADYSTART = _descriptor.Descriptor(
  name='C_S_DoReadyStart',
  full_name='common.C_S_DoReadyStart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='common.C_S_DoReadyStart.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=24,
  serialized_end=58,
)


_S_C_PLAYERREADYRESULT_PLAYER_INFO = _descriptor.Descriptor(
  name='player_info',
  full_name='common.S_C_PlayerReadyResult.player_info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='side', full_name='common.S_C_PlayerReadyResult.player_info.side', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result', full_name='common.S_C_PlayerReadyResult.player_info.result', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=151,
  serialized_end=194,
)

_S_C_PLAYERREADYRESULT = _descriptor.Descriptor(
  name='S_C_PlayerReadyResult',
  full_name='common.S_C_PlayerReadyResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='PlayerResult', full_name='common.S_C_PlayerReadyResult.PlayerResult', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_S_C_PLAYERREADYRESULT_PLAYER_INFO, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=61,
  serialized_end=194,
)


_C_S_ONPROXY = _descriptor.Descriptor(
  name='C_S_OnProxy',
  full_name='common.C_S_OnProxy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='choice', full_name='common.C_S_OnProxy.choice', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=196,
  serialized_end=225,
)


_S_C_PROXY_S_C_ISPROXY = _descriptor.Descriptor(
  name='S_C_IsProxy',
  full_name='common.S_C_Proxy.S_C_IsProxy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='side', full_name='common.S_C_Proxy.S_C_IsProxy.side', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isproxy', full_name='common.S_C_Proxy.S_C_IsProxy.isproxy', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=285,
  serialized_end=329,
)

_S_C_PROXY = _descriptor.Descriptor(
  name='S_C_Proxy',
  full_name='common.S_C_Proxy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='common.S_C_Proxy.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_S_C_PROXY_S_C_ISPROXY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=227,
  serialized_end=329,
)

_S_C_PLAYERREADYRESULT_PLAYER_INFO.containing_type = _S_C_PLAYERREADYRESULT;
_S_C_PLAYERREADYRESULT.fields_by_name['PlayerResult'].message_type = _S_C_PLAYERREADYRESULT_PLAYER_INFO
_S_C_PROXY_S_C_ISPROXY.containing_type = _S_C_PROXY;
_S_C_PROXY.fields_by_name['data'].message_type = _S_C_PROXY_S_C_ISPROXY
DESCRIPTOR.message_types_by_name['C_S_DoReadyStart'] = _C_S_DOREADYSTART
DESCRIPTOR.message_types_by_name['S_C_PlayerReadyResult'] = _S_C_PLAYERREADYRESULT
DESCRIPTOR.message_types_by_name['C_S_OnProxy'] = _C_S_ONPROXY
DESCRIPTOR.message_types_by_name['S_C_Proxy'] = _S_C_PROXY

class C_S_DoReadyStart(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _C_S_DOREADYSTART

  # @@protoc_insertion_point(class_scope:common.C_S_DoReadyStart)

class S_C_PlayerReadyResult(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class player_info(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _S_C_PLAYERREADYRESULT_PLAYER_INFO

    # @@protoc_insertion_point(class_scope:common.S_C_PlayerReadyResult.player_info)
  DESCRIPTOR = _S_C_PLAYERREADYRESULT

  # @@protoc_insertion_point(class_scope:common.S_C_PlayerReadyResult)

class C_S_OnProxy(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _C_S_ONPROXY

  # @@protoc_insertion_point(class_scope:common.C_S_OnProxy)

class S_C_Proxy(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class S_C_IsProxy(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _S_C_PROXY_S_C_ISPROXY

    # @@protoc_insertion_point(class_scope:common.S_C_Proxy.S_C_IsProxy)
  DESCRIPTOR = _S_C_PROXY

  # @@protoc_insertion_point(class_scope:common.S_C_Proxy)


# @@protoc_insertion_point(module_scope)
