# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: private_mahjong.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='private_mahjong.proto',
  package='private_mahjong',
  serialized_pb='\n\x15private_mahjong.proto\x12\x0fprivate_mahjong\"$\n\x12S_C_BanInteraction\x12\x0e\n\x06result\x18\x01 \x02(\x08*%\n\nMSG_HEADER\x12\x17\n\x12S_C_BANINTERACTION\x10\xa2\x44')

_MSG_HEADER = _descriptor.EnumDescriptor(
  name='MSG_HEADER',
  full_name='private_mahjong.MSG_HEADER',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='S_C_BANINTERACTION', index=0, number=8738,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=80,
  serialized_end=117,
)

MSG_HEADER = enum_type_wrapper.EnumTypeWrapper(_MSG_HEADER)
S_C_BANINTERACTION = 8738



_S_C_BANINTERACTION = _descriptor.Descriptor(
  name='S_C_BanInteraction',
  full_name='private_mahjong.S_C_BanInteraction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='private_mahjong.S_C_BanInteraction.result', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=42,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['S_C_BanInteraction'] = _S_C_BANINTERACTION

class S_C_BanInteraction(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _S_C_BANINTERACTION

  # @@protoc_insertion_point(class_scope:private_mahjong.S_C_BanInteraction)


# @@protoc_insertion_point(module_scope)
