# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: replay4proto.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='replay4proto.proto',
  package='replay4proto',
  serialized_pb='\n\x12replay4proto.proto\x12\x0creplay4proto\"G\n\nActionData\x12\x0f\n\x07msgCode\x18\x01 \x02(\x07\x12\x15\n\rreplayMessage\x18\x02 \x02(\x0c\x12\x11\n\ttimestamp\x18\x03 \x02(\x06\"(\n\tTilesData\x12\x0c\n\x04side\x18\x01 \x02(\x07\x12\r\n\x05tiles\x18\x02 \x02(\x0c\"w\n\nReplayData\x12&\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x18.replay4proto.ActionData\x12\x13\n\x0bprivateData\x18\x02 \x02(\x0c\x12,\n\x0bmahjongData\x18\x03 \x03(\x0b\x32\x17.replay4proto.TilesData')




_ACTIONDATA = _descriptor.Descriptor(
  name='ActionData',
  full_name='replay4proto.ActionData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgCode', full_name='replay4proto.ActionData.msgCode', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='replayMessage', full_name='replay4proto.ActionData.replayMessage', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='replay4proto.ActionData.timestamp', index=2,
      number=3, type=6, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=36,
  serialized_end=107,
)


_TILESDATA = _descriptor.Descriptor(
  name='TilesData',
  full_name='replay4proto.TilesData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='side', full_name='replay4proto.TilesData.side', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tiles', full_name='replay4proto.TilesData.tiles', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=109,
  serialized_end=149,
)


_REPLAYDATA = _descriptor.Descriptor(
  name='ReplayData',
  full_name='replay4proto.ReplayData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='replay4proto.ReplayData.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='privateData', full_name='replay4proto.ReplayData.privateData', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mahjongData', full_name='replay4proto.ReplayData.mahjongData', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=151,
  serialized_end=270,
)

_REPLAYDATA.fields_by_name['data'].message_type = _ACTIONDATA
_REPLAYDATA.fields_by_name['mahjongData'].message_type = _TILESDATA
DESCRIPTOR.message_types_by_name['ActionData'] = _ACTIONDATA
DESCRIPTOR.message_types_by_name['TilesData'] = _TILESDATA
DESCRIPTOR.message_types_by_name['ReplayData'] = _REPLAYDATA

class ActionData(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACTIONDATA

  # @@protoc_insertion_point(class_scope:replay4proto.ActionData)

class TilesData(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TILESDATA

  # @@protoc_insertion_point(class_scope:replay4proto.TilesData)

class ReplayData(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REPLAYDATA

  # @@protoc_insertion_point(class_scope:replay4proto.ReplayData)


# @@protoc_insertion_point(module_scope)
