# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trasfer.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='trasfer.proto',
  package='trasfer',
  serialized_pb='\n\rtrasfer.proto\x12\x07trasfer\"t\n\x15S_S_MysqlCommandsData\x12\x34\n\x08\x63ommands\x18\x01 \x03(\x0b\x32\".trasfer.S_S_MysqlCommandsData.com\x1a%\n\x03\x63om\x12\x10\n\x08\x63ommands\x18\x01 \x02(\t\x12\x0c\n\x04type\x18\x02 \x02(\x07\")\n\x15S_S_RedisCommandsData\x12\x10\n\x08\x63ommands\x18\x01 \x03(\t*H\n\nMSG_HEADER\x12\x1c\n\x17S_S_MYSQL_COMMANDS_DATA\x10\x99\x61\x12\x1c\n\x17S_S_REDIS_COMMANDS_DATA\x10\x82`')

_MSG_HEADER = _descriptor.EnumDescriptor(
  name='MSG_HEADER',
  full_name='trasfer.MSG_HEADER',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='S_S_MYSQL_COMMANDS_DATA', index=0, number=12441,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S_S_REDIS_COMMANDS_DATA', index=1, number=12290,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=187,
  serialized_end=259,
)

MSG_HEADER = enum_type_wrapper.EnumTypeWrapper(_MSG_HEADER)
S_S_MYSQL_COMMANDS_DATA = 12441
S_S_REDIS_COMMANDS_DATA = 12290



_S_S_MYSQLCOMMANDSDATA_COM = _descriptor.Descriptor(
  name='com',
  full_name='trasfer.S_S_MysqlCommandsData.com',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='commands', full_name='trasfer.S_S_MysqlCommandsData.com.commands', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='trasfer.S_S_MysqlCommandsData.com.type', index=1,
      number=2, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=105,
  serialized_end=142,
)

_S_S_MYSQLCOMMANDSDATA = _descriptor.Descriptor(
  name='S_S_MysqlCommandsData',
  full_name='trasfer.S_S_MysqlCommandsData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='commands', full_name='trasfer.S_S_MysqlCommandsData.commands', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_S_S_MYSQLCOMMANDSDATA_COM, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=26,
  serialized_end=142,
)


_S_S_REDISCOMMANDSDATA = _descriptor.Descriptor(
  name='S_S_RedisCommandsData',
  full_name='trasfer.S_S_RedisCommandsData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='commands', full_name='trasfer.S_S_RedisCommandsData.commands', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=144,
  serialized_end=185,
)

_S_S_MYSQLCOMMANDSDATA_COM.containing_type = _S_S_MYSQLCOMMANDSDATA;
_S_S_MYSQLCOMMANDSDATA.fields_by_name['commands'].message_type = _S_S_MYSQLCOMMANDSDATA_COM
DESCRIPTOR.message_types_by_name['S_S_MysqlCommandsData'] = _S_S_MYSQLCOMMANDSDATA
DESCRIPTOR.message_types_by_name['S_S_RedisCommandsData'] = _S_S_REDISCOMMANDSDATA

class S_S_MysqlCommandsData(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class com(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _S_S_MYSQLCOMMANDSDATA_COM

    # @@protoc_insertion_point(class_scope:trasfer.S_S_MysqlCommandsData.com)
  DESCRIPTOR = _S_S_MYSQLCOMMANDSDATA

  # @@protoc_insertion_point(class_scope:trasfer.S_S_MysqlCommandsData)

class S_S_RedisCommandsData(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _S_S_REDISCOMMANDSDATA

  # @@protoc_insertion_point(class_scope:trasfer.S_S_RedisCommandsData)


# @@protoc_insertion_point(module_scope)
