# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: autoCreateRoom.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='autoCreateRoom.proto',
  package='autoCreateRoom',
  serialized_pb='\n\x14\x61utoCreateRoom.proto\x12\x0e\x61utoCreateRoom\"\x84\x01\n\x12S_S_AutoCreateRoom\x12\n\n\x02id\x18\x01 \x02(\x07\x12\x0c\n\x04rule\x18\x02 \x02(\t\x12\x11\n\ttimestamp\x18\x03 \x02(\t\x12\x0f\n\x07\x61\x63\x63ount\x18\x04 \x02(\t\x12\n\n\x02\x61g\x18\x05 \x02(\t\x12\x10\n\x08ruleText\x18\x06 \x02(\t\x12\x12\n\nclubNumber\x18\x07 \x02(\t*%\n\nMSG_HEADER\x12\x17\n\x12S_S_AUTOCREATEROOM\x10\x99\x41')

_MSG_HEADER = _descriptor.EnumDescriptor(
  name='MSG_HEADER',
  full_name='autoCreateRoom.MSG_HEADER',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='S_S_AUTOCREATEROOM', index=0, number=8345,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=175,
  serialized_end=212,
)

MSG_HEADER = enum_type_wrapper.EnumTypeWrapper(_MSG_HEADER)
S_S_AUTOCREATEROOM = 8345



_S_S_AUTOCREATEROOM = _descriptor.Descriptor(
  name='S_S_AutoCreateRoom',
  full_name='autoCreateRoom.S_S_AutoCreateRoom',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='autoCreateRoom.S_S_AutoCreateRoom.id', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rule', full_name='autoCreateRoom.S_S_AutoCreateRoom.rule', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='autoCreateRoom.S_S_AutoCreateRoom.timestamp', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='account', full_name='autoCreateRoom.S_S_AutoCreateRoom.account', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ag', full_name='autoCreateRoom.S_S_AutoCreateRoom.ag', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ruleText', full_name='autoCreateRoom.S_S_AutoCreateRoom.ruleText', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clubNumber', full_name='autoCreateRoom.S_S_AutoCreateRoom.clubNumber', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=41,
  serialized_end=173,
)

DESCRIPTOR.message_types_by_name['S_S_AutoCreateRoom'] = _S_S_AUTOCREATEROOM

class S_S_AutoCreateRoom(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _S_S_AUTOCREATEROOM

  # @@protoc_insertion_point(class_scope:autoCreateRoom.S_S_AutoCreateRoom)


# @@protoc_insertion_point(module_scope)
