# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: guangxi_mahjong.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='guangxi_mahjong.proto',
  package='guangxi_mahjong',
  serialized_pb='\n\x15guangxi_mahjong.proto\x12\x0fguangxi_mahjong\"4\n\x0cS_C_RunHorse\x12\x12\n\nHorsetiles\x18\x01 \x03(\t\x12\x10\n\x08WinHorse\x18\x02 \x03(\t*\x1f\n\nMSG_HEADER\x12\x11\n\x0cS_C_RUNHORSE\x10\x81`')

_MSG_HEADER = _descriptor.EnumDescriptor(
  name='MSG_HEADER',
  full_name='guangxi_mahjong.MSG_HEADER',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='S_C_RUNHORSE', index=0, number=12289,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=96,
  serialized_end=127,
)

MSG_HEADER = enum_type_wrapper.EnumTypeWrapper(_MSG_HEADER)
S_C_RUNHORSE = 12289



_S_C_RUNHORSE = _descriptor.Descriptor(
  name='S_C_RunHorse',
  full_name='guangxi_mahjong.S_C_RunHorse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Horsetiles', full_name='guangxi_mahjong.S_C_RunHorse.Horsetiles', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='WinHorse', full_name='guangxi_mahjong.S_C_RunHorse.WinHorse', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=42,
  serialized_end=94,
)

DESCRIPTOR.message_types_by_name['S_C_RunHorse'] = _S_C_RUNHORSE

class S_C_RunHorse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _S_C_RUNHORSE

  # @@protoc_insertion_point(class_scope:guangxi_mahjong.S_C_RunHorse)


# @@protoc_insertion_point(module_scope)
