declare function getLanguage():string
declare function getShowOtherWallet():boolean
declare function getSelectServerSwitchState():boolean
declare function isPublicLock(gid):boolean
declare function isPublicVersion():boolean
declare function isPrintURL():boolean
declare function isPrintProtoCmd():boolean
declare function isTestSpeed():boolean
declare function getTSConfigs():Array<string>
declare function getResRoot():string
declare function getTextResRoot():string
declare function getLoginType():number
declare function isHotGame(game:string):boolean
declare function AllFundVisible():boolean
declare function getGameSubPageType(gameid:number):number
declare function getQueryString(name:string):string
declare function callJsOpenWindow(target_url:string)
declare function getCodeAdapter():ICoder