# -*- coding:utf-8 -*-
# !/bin/python

# KongHu = u'杠上开花'
# TianDiHu = u'天地胡'
#
# EighteenHu = u'十八罗汉'
# ThirteenOrphans = u'十三幺'
# ALLFlowHu = u'全风碰'
# TianHu = u'天胡'
# DiHu = u'地胡'
# YaoNine = u'幺九胡'
# DoubleSuperSevenPair = u'双豪华七对'
# SuperSevenPair = u'豪华七对'
# OneColourPongHu = u'清碰胡'
# OneColour = u'清一色'
# MixColourPongHu = u'混碰胡'
# SevenPair = u'七小对'
# AllPong = u'碰碰胡'
# MixColour = u'混一色'
# PingHu = u'鸡胡'

BeGrabKongHu = u'抢杠胡'
KongHu = u'杠上开花'
SeeMoon = u'海底捞月'
TianHu = u'天胡'
DiHu = u'地胡'

PingHu = u'鸡胡'
PongHu = u'碰碰胡'
MixColourHu = u'混一色'
OneColourHu = u'清一色'
SevenPairHu = u'七对'
SuperSevenPairHu = u'豪华七对'
MixYaoNine = u'混幺九'
ZiColourHu = u'字一色'
CleanYaoNine = u'清幺九'
ThirteenOrphans = u'十三幺'
SmallThreeHu = u'小三元'
SmallFourHu = u'小四喜'
BigThreeHu = u'大三元'
BigFourHu = u'大四喜'
