# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hainan_mahjong.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hainan_mahjong.proto',
  package='hainan_mahjong',
  serialized_pb='\n\x14hainan_mahjong.proto\x12\x0ehainan_mahjong\"\x16\n\x08\x43_S_OnGa\x12\n\n\x02ga\x18\x01 \x02(\x07\"\x1e\n\nS_C_GaData\x12\x10\n\x08\x63\x61nGetGa\x18\x02 \x03(\x07\"\x8d\x01\n\rS_C_Ga_Choose\x12\x35\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\'.hainan_mahjong.S_C_Ga_Choose.GaGetData\x12\x0e\n\x06result\x18\x02 \x02(\x08\x12\x0e\n\x06reason\x18\x03 \x01(\t\x1a%\n\tGaGetData\x12\x0c\n\x04side\x18\x01 \x02(\x07\x12\n\n\x02ga\x18\x02 \x02(\x07\"+\n\rS_C_Flower_Hu\x12\x0c\n\x04side\x18\x01 \x02(\x07\x12\x0c\n\x04rate\x18\x02 \x02(\x07\"L\n\x13S_C_Be_Handle_Tiles\x12\x0c\n\x04nums\x18\x01 \x02(\x07\x12\x13\n\x0b\x64iscardSide\x18\x02 \x02(\x07\x12\x12\n\nactionSide\x18\x03 \x02(\x07\"\x1d\n\rS_C_Be_Follow\x12\x0c\n\x04side\x18\x01 \x02(\x07\"\x1b\n\x0bS_C_Be_Kong\x12\x0c\n\x04side\x18\x01 \x02(\x07\"\x1f\n\x0fS_C_Be_Surround\x12\x0c\n\x04side\x18\x01 \x02(\x07\"\x1d\n\tS_C_Order\x12\x10\n\x08orderNum\x18\x01 \x02(\x07*\xc1\x01\n\nMSG_HEADER\x12\x0e\n\tC_S_ON_GA\x10\x81@\x12\x10\n\x0bS_C_GA_DATA\x10\x81`\x12\x13\n\rS_C_GA_CHOOSE\x10\x82\x80\x0c\x12\x12\n\rS_C_FLOWER_HU\x10\x83`\x12\x18\n\x13S_C_BE_HANDLE_TILES\x10\x84`\x12\x13\n\rS_C_BE_FOLLOW\x10\x85\x80\x0c\x12\x11\n\x0bS_C_BE_KONG\x10\x86\x80\x0c\x12\x15\n\x0fS_C_BE_SURROUND\x10\x87\x80\x0c\x12\x0f\n\tS_C_ORDER\x10\x88\x80\x0c')

_MSG_HEADER = _descriptor.EnumDescriptor(
  name='MSG_HEADER',
  full_name='hainan_mahjong.MSG_HEADER',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='C_S_ON_GA', index=0, number=8193,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S_C_GA_DATA', index=1, number=12289,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S_C_GA_CHOOSE', index=2, number=196610,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S_C_FLOWER_HU', index=3, number=12291,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S_C_BE_HANDLE_TILES', index=4, number=12292,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S_C_BE_FOLLOW', index=5, number=196613,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S_C_BE_KONG', index=6, number=196614,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S_C_BE_SURROUND', index=7, number=196615,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S_C_ORDER', index=8, number=196616,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=488,
  serialized_end=681,
)

MSG_HEADER = enum_type_wrapper.EnumTypeWrapper(_MSG_HEADER)
C_S_ON_GA = 8193
S_C_GA_DATA = 12289
S_C_GA_CHOOSE = 196610
S_C_FLOWER_HU = 12291
S_C_BE_HANDLE_TILES = 12292
S_C_BE_FOLLOW = 196613
S_C_BE_KONG = 196614
S_C_BE_SURROUND = 196615
S_C_ORDER = 196616



_C_S_ONGA = _descriptor.Descriptor(
  name='C_S_OnGa',
  full_name='hainan_mahjong.C_S_OnGa',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ga', full_name='hainan_mahjong.C_S_OnGa.ga', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=40,
  serialized_end=62,
)


_S_C_GADATA = _descriptor.Descriptor(
  name='S_C_GaData',
  full_name='hainan_mahjong.S_C_GaData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='canGetGa', full_name='hainan_mahjong.S_C_GaData.canGetGa', index=0,
      number=2, type=7, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=64,
  serialized_end=94,
)


_S_C_GA_CHOOSE_GAGETDATA = _descriptor.Descriptor(
  name='GaGetData',
  full_name='hainan_mahjong.S_C_Ga_Choose.GaGetData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='side', full_name='hainan_mahjong.S_C_Ga_Choose.GaGetData.side', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ga', full_name='hainan_mahjong.S_C_Ga_Choose.GaGetData.ga', index=1,
      number=2, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=201,
  serialized_end=238,
)

_S_C_GA_CHOOSE = _descriptor.Descriptor(
  name='S_C_Ga_Choose',
  full_name='hainan_mahjong.S_C_Ga_Choose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='hainan_mahjong.S_C_Ga_Choose.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result', full_name='hainan_mahjong.S_C_Ga_Choose.result', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reason', full_name='hainan_mahjong.S_C_Ga_Choose.reason', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_S_C_GA_CHOOSE_GAGETDATA, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=97,
  serialized_end=238,
)


_S_C_FLOWER_HU = _descriptor.Descriptor(
  name='S_C_Flower_Hu',
  full_name='hainan_mahjong.S_C_Flower_Hu',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='side', full_name='hainan_mahjong.S_C_Flower_Hu.side', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rate', full_name='hainan_mahjong.S_C_Flower_Hu.rate', index=1,
      number=2, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=240,
  serialized_end=283,
)


_S_C_BE_HANDLE_TILES = _descriptor.Descriptor(
  name='S_C_Be_Handle_Tiles',
  full_name='hainan_mahjong.S_C_Be_Handle_Tiles',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nums', full_name='hainan_mahjong.S_C_Be_Handle_Tiles.nums', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='discardSide', full_name='hainan_mahjong.S_C_Be_Handle_Tiles.discardSide', index=1,
      number=2, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='actionSide', full_name='hainan_mahjong.S_C_Be_Handle_Tiles.actionSide', index=2,
      number=3, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=285,
  serialized_end=361,
)


_S_C_BE_FOLLOW = _descriptor.Descriptor(
  name='S_C_Be_Follow',
  full_name='hainan_mahjong.S_C_Be_Follow',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='side', full_name='hainan_mahjong.S_C_Be_Follow.side', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=363,
  serialized_end=392,
)


_S_C_BE_KONG = _descriptor.Descriptor(
  name='S_C_Be_Kong',
  full_name='hainan_mahjong.S_C_Be_Kong',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='side', full_name='hainan_mahjong.S_C_Be_Kong.side', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=394,
  serialized_end=421,
)


_S_C_BE_SURROUND = _descriptor.Descriptor(
  name='S_C_Be_Surround',
  full_name='hainan_mahjong.S_C_Be_Surround',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='side', full_name='hainan_mahjong.S_C_Be_Surround.side', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=423,
  serialized_end=454,
)


_S_C_ORDER = _descriptor.Descriptor(
  name='S_C_Order',
  full_name='hainan_mahjong.S_C_Order',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='orderNum', full_name='hainan_mahjong.S_C_Order.orderNum', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=456,
  serialized_end=485,
)

_S_C_GA_CHOOSE_GAGETDATA.containing_type = _S_C_GA_CHOOSE;
_S_C_GA_CHOOSE.fields_by_name['data'].message_type = _S_C_GA_CHOOSE_GAGETDATA
DESCRIPTOR.message_types_by_name['C_S_OnGa'] = _C_S_ONGA
DESCRIPTOR.message_types_by_name['S_C_GaData'] = _S_C_GADATA
DESCRIPTOR.message_types_by_name['S_C_Ga_Choose'] = _S_C_GA_CHOOSE
DESCRIPTOR.message_types_by_name['S_C_Flower_Hu'] = _S_C_FLOWER_HU
DESCRIPTOR.message_types_by_name['S_C_Be_Handle_Tiles'] = _S_C_BE_HANDLE_TILES
DESCRIPTOR.message_types_by_name['S_C_Be_Follow'] = _S_C_BE_FOLLOW
DESCRIPTOR.message_types_by_name['S_C_Be_Kong'] = _S_C_BE_KONG
DESCRIPTOR.message_types_by_name['S_C_Be_Surround'] = _S_C_BE_SURROUND
DESCRIPTOR.message_types_by_name['S_C_Order'] = _S_C_ORDER

class C_S_OnGa(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _C_S_ONGA

  # @@protoc_insertion_point(class_scope:hainan_mahjong.C_S_OnGa)

class S_C_GaData(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _S_C_GADATA

  # @@protoc_insertion_point(class_scope:hainan_mahjong.S_C_GaData)

class S_C_Ga_Choose(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class GaGetData(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _S_C_GA_CHOOSE_GAGETDATA

    # @@protoc_insertion_point(class_scope:hainan_mahjong.S_C_Ga_Choose.GaGetData)
  DESCRIPTOR = _S_C_GA_CHOOSE

  # @@protoc_insertion_point(class_scope:hainan_mahjong.S_C_Ga_Choose)

class S_C_Flower_Hu(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _S_C_FLOWER_HU

  # @@protoc_insertion_point(class_scope:hainan_mahjong.S_C_Flower_Hu)

class S_C_Be_Handle_Tiles(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _S_C_BE_HANDLE_TILES

  # @@protoc_insertion_point(class_scope:hainan_mahjong.S_C_Be_Handle_Tiles)

class S_C_Be_Follow(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _S_C_BE_FOLLOW

  # @@protoc_insertion_point(class_scope:hainan_mahjong.S_C_Be_Follow)

class S_C_Be_Kong(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _S_C_BE_KONG

  # @@protoc_insertion_point(class_scope:hainan_mahjong.S_C_Be_Kong)

class S_C_Be_Surround(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _S_C_BE_SURROUND

  # @@protoc_insertion_point(class_scope:hainan_mahjong.S_C_Be_Surround)

class S_C_Order(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _S_C_ORDER

  # @@protoc_insertion_point(class_scope:hainan_mahjong.S_C_Order)


# @@protoc_insertion_point(module_scope)
