# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clubOpenRoom.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='clubOpenRoom.proto',
  package='autoCreateRoom',
  serialized_pb='\n\x12\x63lubOpenRoom.proto\x12\x0e\x61utoCreateRoom\"\x92\x01\n\x10S_S_ClubOpenRoom\x12\n\n\x02id\x18\x01 \x02(\x07\x12\x0c\n\x04rule\x18\x02 \x02(\t\x12\x11\n\ttimestamp\x18\x03 \x02(\t\x12\x0f\n\x07\x61\x63\x63ount\x18\x04 \x02(\t\x12\n\n\x02\x61g\x18\x05 \x02(\t\x12\x10\n\x08ruleText\x18\x06 \x02(\t\x12\x12\n\nclubNumber\x18\x07 \x02(\t\x12\x0e\n\x06roomId\x18\x08 \x02(\t*#\n\nMSG_HEADER\x12\x15\n\x10S_S_CLUBOPENROOM\x10\x98\x41')

_MSG_HEADER = _descriptor.EnumDescriptor(
  name='MSG_HEADER',
  full_name='autoCreateRoom.MSG_HEADER',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='S_S_CLUBOPENROOM', index=0, number=8344,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=187,
  serialized_end=222,
)

MSG_HEADER = enum_type_wrapper.EnumTypeWrapper(_MSG_HEADER)
S_S_CLUBOPENROOM = 8344



_S_S_CLUBOPENROOM = _descriptor.Descriptor(
  name='S_S_ClubOpenRoom',
  full_name='autoCreateRoom.S_S_ClubOpenRoom',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='autoCreateRoom.S_S_ClubOpenRoom.id', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rule', full_name='autoCreateRoom.S_S_ClubOpenRoom.rule', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='autoCreateRoom.S_S_ClubOpenRoom.timestamp', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='account', full_name='autoCreateRoom.S_S_ClubOpenRoom.account', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ag', full_name='autoCreateRoom.S_S_ClubOpenRoom.ag', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ruleText', full_name='autoCreateRoom.S_S_ClubOpenRoom.ruleText', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clubNumber', full_name='autoCreateRoom.S_S_ClubOpenRoom.clubNumber', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='roomId', full_name='autoCreateRoom.S_S_ClubOpenRoom.roomId', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=39,
  serialized_end=185,
)

DESCRIPTOR.message_types_by_name['S_S_ClubOpenRoom'] = _S_S_CLUBOPENROOM

class S_S_ClubOpenRoom(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _S_S_CLUBOPENROOM

  # @@protoc_insertion_point(class_scope:autoCreateRoom.S_S_ClubOpenRoom)


# @@protoc_insertion_point(module_scope)
